joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

egm_state_controller:
  type         : abb_egm_state_controller/EGMStateController
  publish_rate : 250

# These settings must match:
# - Joint names extracted from the ABB robot controller.
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - crb1100_580_joint_1
    - crb1100_580_joint_2
    - crb1100_580_joint_3
    - crb1100_580_joint_4
    - crb1100_580_joint_5
    - crb1100_580_joint_6

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: 
    - crb1100_580_joint_1
    - crb1100_580_joint_2
    - crb1100_580_joint_3
    - crb1100_580_joint_4
    - crb1100_580_joint_5
    - crb1100_580_joint_6

joint_velocity_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: [crb1100_580_joint_1, crb1100_580_joint_2, crb1100_580_joint_3, crb1100_580_joint_4, crb1100_580_joint_5, crb1100_580_joint_6]
  gains:
    crb1100_580_joint_1: {p: 100, i: 1, d: 1, i_clamp: 1}
    crb1100_580_joint_2: {p: 100, i: 1, d: 1, i_clamp: 1}
    crb1100_580_joint_3: {p: 100, i: 1, d: 1, i_clamp: 1}
    crb1100_580_joint_4: {p: 100, i: 1, d: 1, i_clamp: 1}
    crb1100_580_joint_5: {p: 100, i: 1, d: 1, i_clamp: 1}
    crb1100_580_joint_6: {p: 100, i: 1, d: 1, i_clamp: 1}

joint_position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: [crb1100_580_joint_1, crb1100_580_joint_2, crb1100_580_joint_3, crb1100_580_joint_4, crb1100_580_joint_5, crb1100_580_joint_6]
  constraints:
      goal_time: 10                # Override default
      stopped_velocity_tolerance: 0.1 # Override default
      stop_trajectory_duration: 0.0
      crb1100_580_joint_1:
        goal: 0.015
      crb1100_580_joint_2:
        goal: 0.015
      crb1100_580_joint_3:
        goal: 0.015
      crb1100_580_joint_4:
        goal: 0.015
      crb1100_580_joint_5:
        goal: 0.015
      crb1100_580_joint_6:
        goal: 0.015