joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

egm_state_controller:
  type         : abb_egm_state_controller/EGMStateController
  publish_rate : 250

# These settings must match:
# - Joint names extracted from the ABB robot controller.
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: 
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

joint_velocity_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  gains:
    joint_1: {p: 100, i: 1, d: 1, i_clamp: 1}
    joint_2: {p: 100, i: 1, d: 1, i_clamp: 1}
    joint_3: {p: 100, i: 1, d: 1, i_clamp: 1}
    joint_4: {p: 100, i: 1, d: 1, i_clamp: 1}
    joint_5: {p: 100, i: 1, d: 1, i_clamp: 1}
    joint_6: {p: 100, i: 1, d: 1, i_clamp: 1}

joint_position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  constraints:
    goal_time: 10                 # Override default
    stopped_velocity_tolerance: 0.02 # Override default
    stop_trajectory_duration: 0.0
